.ORIG x3000
LD R4, ASCII_0M
IN
ADD R1, R0, R4
IN
ADD R2, R0, R4
NOT R3, R2
ADD R3, R3, #1
ADD R5, R1, R3
BRn SMALLER
BRp GREATER
LEA R0, STR_OUT_3
BR PRINT
GREATER  LEA R0, STR_OUT_2
         BR PRINT
SMALLER  LEA R0, STR_OUT_1
PRINT    PUTS
STR_OUT_1 .STRINGZ "A be hon B"
STR_OUT_2 .STRINGZ "A lon hon B"
STR_OUT_3 .STRINGZ "Hai so bang nhau"
ASCII_0     .FILL #48
ASCII_0M     .FILL #-48

.END